name: Docker Image CI

on:
  push:
  pull_request:
    types: [opened, reopened]
    

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cardboard-build-test:$(date +%s)
